[workspace]
members = [
    "aoc1",
    "aoc2",
    "aoc3",
    "aoc4",
    "aoc5",
    "aoc6",
    "aoc7",
    "aoc8",
    "aoc9",
    "aoc10",
    "aoc11",
    "aoc13",
    "aoc14",
    "aoc15",
    "aoc16",
    "aoc17",
    "aoc18",
    "aoc19",
    "aoc25",
]
resolver = "2"
